#!/bin/bash
#-------------------------------------------------------------------------------
# es7s/holms
# (c) 2023 A. Shavykin <0.delameter@gmail.com>
#-------------------------------------------------------------------------------

PATHS=(
  ".hatch/dev/bin"
  "venv/bin"
)

__locate_venv() {
  local srcpath="$1"
  for file in "${PATHS[@]/%//python}" ; do
      file="$srcpath/$file"
      [[ -x $file ]] && echo "$file" && return 0
  done
  return 1
}

__main() {
    local srcpath=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
    local python=
    if ! python=$(__locate_venv "$srcpath") ; then
        echo "Installed application not found, run 'make reinit-manual-venv'"
        exit 1
    fi
    PYTHONPATH="$srcpath" "$python" -m holms "$@"
}

__main "$@"
