#!/bin/bash

function _die {
    echo "ERROR:" "$*"
    echo "USAGE:"
    echo "    $0 TERM"
    echo "EXAMPLES:"
    echo "    $0 dash"
    echo "    $0 numb.+"
    exit 1
}
[[ $# -eq 0 ]] && _die "Search term/regexp expected"

unzip -c misc/unicode_chart.zip | grep -iEe "${*}"
